name: new_auto_route

packages:
  - packages/**

command:
  bootstrap:
    usePubspecOverrides: true
    # https://github.com/dart-lang/pub/issues/3404)
    runPubGetInParallel: false

ide:
  intellij: false

scripts:
  codegen:
    run: melos exec -- "flutter pub run build_runner build --delete-conflicting-outputs"
    description: Run codegen in app package
    select-package:
      scope: "app_*"
