name: app_old
description: App using old auto_router
publish_to: none
version: 0.0.1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  auto_route: ^5.0.4
  page_a_old:
  page_b_old:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  auto_route_generator: ^5.0.3
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
